### ISSUE TITLE
How to reload the config when sql_exporter is still running?

### ISSUE THREAD

**Issue by tangxuye** [free/sql_exporter#12]
Well, I mean ,
      If the configuration file has been modified.How to reload it when sql_exporter is running  on a linux server? This is similar to the Ngnix command: nginx -s reload. Sometimes restart service or kill the process is not very suitable in the production environment.

**Comment by free** [comment]
There is currently no such functionality, but I'm happy to integrate it should someone want to write it.

Shouldn't be all that difficult to implement either: something along the lines of https://github.com/AnchorFree/jira-alerter/blob/master/jiralert/cmd/jiralert/main.go, but slightly more structured. :o)

**Comment by tangxuye** [comment]
OK，I expect it will be realized soon,thank for your reply.
