### ISSUE TITLE
How many data_source can sql_exporter configure?

### ISSUE THREAD

**Issue by tangxuye** [free/sql_exporter#14]
Hi,
I have a confusion.It is that how many data_source can be configured in the 'sql_exporter.yaml' file.I tried to type two data_source_name under the target node,but it was running  with error_log.

**Comment by free** [comment]
There exists an undocumented feature that allows you to scrape multiple data sources from a single SQL Exporter, but I would strongly recommend against it. The only situation where it would reasonably make sense to use it is if you have multiple database instances running on the same VM.

See issue #6 for details.
