### ISSUE TITLE
ODBC driver support

### ISSUE THREAD

**Issue by taeris** [free/sql_exporter#17]
Hello.
Any plans on adding ODBC driver support?
Cheers.

**Comment by free** [comment]
Not specifically, sorry. But contributions are always welcome.

On a related note, unless you really-really have to, I would recommend against ODBC. A long-long time ago (getting close to 20 years ago now) we were using the JDBC-ODBC bridge in a Java webapp. The problem we ran into was that whenever the driver misbehaved (e.g. it dereferenced a null pointer or whatever) it would bring down the whole web server with it. We decided instead to go with a crappy, open source Java native driver instead and fix the couple of shortcomings it had for our needs. Even though it would crash quite a bit more than the JDBC-ODBC bridge, at least it would only take down the one request, not the whole web server. YMMV.

**Comment by taeris** [comment]
Hi.
Thanks for replying. We're going to follow your advice and not use ODBC as we haven't had much success either.
Closing.
