### ISSUE TITLE
How can I add multiple oracle instances

### ISSUE THREAD

**Issue by gowri427** [free/sql_exporter#27]
Hi Team,

How can i add multiple database instances to "database_exporter.yml" file.I observed that it is taking last database connection string if i added like below
data_source_name: 'oracle://XX/XX@XX:1521/XX'
data_source_name: 'oracle://XX/XX@XX:1521/XX'
data_source_name: 'oracle://XX/XX@XX:1521/XX'
data_source_name: 'oracle://XX/XX@XX:1521/XX'

Please help

**Comment by free** [comment]
There are more ways of answering this, so let me try:

1. SQL Exporter does not support Oracle out of the box. It appears you're using a fork from @corundex, so you should probably ask them.

2. There is a way to set up SQL Exporter to monitor multiple targets (see this [older version of README.md](https://github.com/free/sql_exporter/blob/caf149bcfa2ccacb873e82c7e6bb8014b6a2b81d/README.md#testing-and-development-deployment)), but you need to be aware of the fact that this causes SQL Exporter to become a single point of failure and possibly be affected by network issues that wouldn't affect a sidecar deployment (one SQL Exporter instance per database, running next to the database on the same machine/VM). You'll also have to use a different Prometheus configuration for monitoring SQL Exporter in addition to the databases.
