### ISSUE TITLE
Dockerfile to automated build

### ISSUE THREAD

**Issue by ProgEsteves** [free/sql_exporter#3]
It would be a good idea publish a Dockerfile to automate the project build in a repository, like Docker Hub.

I try this here:
https://hub.docker.com/r/progesteves/sql_exporter

But I think you need an official Dockerfile.

**Comment by free** [comment]
[Apologies for taking so long to respond, I wasn't aware I needed to watch my own projects to get notified of new issues so I never got notified of this.]

Hey Felipe, thanks for contributing the Dockerfile. I've created an [automated build on Docker Hub](https://hub.docker.com/r/githubfree/sql_exporter) and linked it from the README. If you want to add a brief description of how to run the image in Docker, I'm more than happy to merge it in. My experience with Docker is limited to a tutorial I ran through once.
