### ISSUE TITLE
Last gathering time in SQL query

### ISSUE THREAD

**Issue by Feudoor** [free/sql_exporter#32]
Is it possible to pass scrape interval into SQL query? It would be useful to get information for last <scrape_interval> seconds.
For example, query may look like this:
``SELECT COUNT(*) FROM <TABLE> WHERE <TABLE>.TIME > NOW() - <scrape_interval>``

**Comment by free** [comment]
You would have to hardcode said value into your queries, as Prometheus does not provide it to SQL Exporter. The only information Prometheus does provide is the scrape timeout (in the form of a [`X-Prometheus-Scrape-Timeout-Seconds` header](https://www.robustperception.io/configuring-blackbox-exporter-timeouts)), but that is [different from the scrape interval](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration-file). (They are equal by default, at 10 seconds each, but they can be tweaked independently.)
