### ISSUE TITLE
Add tagged builds to Docker Hub

### ISSUE THREAD

**Issue by burningalchemist** [free/sql_exporter#46]
I recently bumped into an issue, when `sql-exporter` is used across the environment, but since the only image tag available in Docker Hub is `latest` it appeared that some containers were still on v0.4 or even v0.3.

Since, you already have automated builds in Docker (#3) and also tagged releases, it's extremely easy to add versioned image tags, so users could explicitly define images and also be aware of versions without looking into logs.

In this case, I'd just recommend to add settings from the following picture (particularly, line three) to Docker Hub settings:
![](https://i.stack.imgur.com/9GpzT.png)

I'm not sure if Docker Hub will pick it up immediately (according to the [ticket](https://success.docker.com/article/trigger-a-build-for-an-automated-build-tag)), so maybe quick re-tag is needed, but it would absolutely great to have them.

I might provide some additional information or help, if needed. :)

**Comment by free** [comment]
Done, AFAICT. In theory new builds should be created for every future tag.

Thanks a lot for the suggestion and explanation.

**Comment by burningalchemist** [comment]
Great! Tag `0.5` is already available. Thanks! 👍

**Comment by free** [comment]
Yeah, the older ones failed though, because there was no `Dockerfile` in any of them yet. (It had been added between `0.4` and `0.5`.)
