### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by samuelthan** [free/sql_exporter#5]
First off, thanks for this exporter.

I've followed through the instructions an install in the following environment:

Windows Server 2008 R2 Datacenter
Microsoft SQL SERVER 2008 R2

I've build this sql_exporter from source using go 1.9.2 windows/amd64
Am using the default example of the yml files except changing the sqlserver:// configuration to use proper login and host.

After running the sql_exporter.exe which starts up fine with the Listening to port 9399 message.
I then browse to the server:9399/metrics page.

And i recieve the following error message.

No metrics gathered, [from Gatherer #1] Login error: read tcp 172.x.x.x:51778->172.x.x.x:1433: wsarecv: An existing connection was forcibly closed by the remote host.

I've double/triple check my connection credentials separately using the Microsoft SQL Server Management Studio and login credentials work correctly.

Any thoughts on why i'm getting this error ?

Thanks

**Comment by free** [comment]
All I could find is https://stackoverflow.com/questions/32373537/golang-tcp-error-wsarecv

Are you getting this as soon as you start up sql_exporter? Or does it work for a while, then you get this?

If the former, it could be that something else than SQL Server is running on port 1433 and it closes the connection because it doesn't understand what the SQL Server driver is telling it. Or else, some kind of firewall...

**Comment by free** [comment]
Actually here's a more likely answer (an issue affecting the SQL Server driver sql_exporter is using): https://github.com/denisenkom/go-mssqldb/issues/42

**Comment by free** [comment]
Apparently adding `encrypt=disable` to the DSN seemed to help some people.

**Comment by samuelthan** [comment]
Thank you for the fantastic support/help !!!!

This solution encrypt=disable  works for me 

WOOHOO !!

**Comment by ruoisua** [comment]
Hi, how to add encrypt= disable to dsn ?
Thanks

**Comment by samuelthan** [comment]
> Hi, how to add encrypt= disable to dsn ?
> Thanks

@ruoisua depends on the DB query string you are using

on the top of my head i think is along the lines of..., its been a while since i use this lol.. try
sqlserver://prom_user:prom_password@dbserver1.example.com:1433?encrypt=disable
