### ISSUE TITLE
Redshift Support

### ISSUE THREAD

**Issue by gaglanihetal** [free/sql_exporter#55]
Hi,

I need to add a Redshift DB for people to add metrics against in sql exporter. I have tried every combination of postgresql/redshift/jdbc but i end up getting Jan 02 17:40:42 prometheus1 sql_exporter[26793]: I0102 17:40:42.782689   26793 promhttp.go:38] Error gathering metrics: [from Gatherer #1] [job="redshift-prod", target="****"] sql: unknown driver "postgresql" (forgotten import?)

These are the configurations that don't work:

redshift_source: 'postgresql://username:password@tcp(host:port)/schema'
redshift_source: 'jdbc:postgresql://username:password@tcp(host:port)/schema'
redshift_source: 'jdbc:redshift://username:password@tcp(host:port)/schema'
redshift_source: 'redshift://username:password@tcp(host:port)/schema'

Maybe I am missing something super basic or redshift is not supported.

I have a similar target for mysql datasource which works fine:
mysql_source: 'mysql://username:password@tcp(host:port)/schema'

Guess my question comes down to: Is Redshift driver supported? If yes, what would the connection string look like? If not, can we expect support for it and when? What are the alternatives?

**Comment by xpando** [comment]
The postgres driver works for me:

```
data_source_name: 'postgres://user:passwd@redshift-host:5439/mydbname'
```

**Comment by gaglanihetal** [comment]
Thank you so much!!! that worked for me as well. Closing out this ticket.
