### ISSUE TITLE
Does config file support multiple targets ?

### ISSUE THREAD

**Issue by lrk** [free/sql_exporter#6]
Hello, 

i'm currently writing an ansible role to deploy and configure your exporter (https://github.com/lrk/ansible-role-prometheus-sql-exporter if you want to check).

I'm not sure if the config file support multiple entries of "target", right now i have a Hash model with multiple targets/datasources configurable, and i generate multiple configuration files (with one target inside).
I have to create multiple systemd services as i want the exporter to run and restart automatically after failure or reboot. each one corresponding to one config file (and one target).

i'm not sure if it was somewere in the documentation, but i haven't found any clues, config.go seems to support multiple (undocumented) jobs, but only one target.

If multiple target per config are not supported, i would like to request that feature

thank you in advance.
best regards

**Comment by free** [comment]
SQL Exporter does in fact support multiple targets, but that feature has been removed from the documentation at the request of the Prometheus team. There are a number of reasons for that, such as SQL Exporter becoming a single point of failure, it not being in the same failure domain (i.e. on the same server) as the target it monitors and replicating Prometheus' job/instance/up/labels model. So I'd recommend you deploy one SQL Exporter instance alongside each database you intend to monitor.

That being said, if you go back a couple of versions (for [`README.md`](https://github.com/free/sql_exporter/blob/caf149bcfa2ccacb873e82c7e6bb8014b6a2b81d/README.md) and [`examples/sql_exporter.yml`](https://github.com/free/sql_exporter/blob/d6b933987a967f244b489e19df6682791fffe4ef/examples/sql_exporter.yml)), you'll find the feature documented.

**Comment by free** [comment]
Oh, and you might find that using the same SQL Exporter instance for multiple targets will cause collection to time out on multiple DB servers when only one DB server is slow.

**Comment by lrk** [comment]
Thank you for those explanations.

**Comment by xxorde** [comment]
You still might want to hint this somewhere.
This feature is quite useful if you have multiple databases in one RDMS instance.
So you only need to start one instance of sql_exporter per, for example, every PostgreSQL-Cluster and not one for every database in every cluster.

**Comment by free** [comment]
Fair enough. It was a requirement for having SQL Exporter listed in the Prometheus docs, but that configuration was aimed squarely at running a single exporter with multiple independent targets.

I guess one could make an argument that this is aimed at multiple instances running on the same host (and document it as such). Or just be vewy-vewy quiet about it. :)

**Comment by xxorde** [comment]
@free I totally understand why it is not a good idea to run your SQL Exporter centralized for independent targets. This should never be recommended!
Maybe it is possible to have a disclaimer or so, that this option is available if you run legacy (not containerized) setups on bare metal or big VMs where you want to host multiple databases per host.
