### ISSUE TITLE
not get packedge when download?

### ISSUE THREAD

**Issue by shawbruno** [free/sql_exporter#60]
Hi, when try the comand " go install github.com/free/sql_exporter/cmd/sql_exporter " in my server linux don't download from my machine, the say in mesage " Can't load package, and i try search here how to get the package but i don't see, and with wget idk how to proced for work .. do u can help me ?

**Comment by shawbruno** [comment]
?

**Comment by free** [comment]
You can download the binaries from here: https://github.com/free/sql_exporter/releases . You probably don't want to build from source.

**Comment by shawbruno** [comment]
ok, for ubuntu i don't see the release

**Comment by free** [comment]
There is no Ubuntu-specific release, only `linux`. The second part of the platform (`amd64`, `i386`, `armv7`, whatever) is the CPU architecture. If you don't know yours, then it's probably `amd64`, so download `sql_exporter-0.5.linux-amd64.tar.gz`.
