### ISSUE TITLE
Password containing %  in SQL URL throws error: invalid URL escape "%xx"

### ISSUE THREAD

**Issue by DandyDeveloper** [free/sql_exporter#66]
I think we need to parse escape characters correctly, looks like we're missing this. 

```
No metrics gathered, [from Gatherer #1] parse sqlserver://user:pass%word@host:3306: invalid URL escape "%bt"
```

**Comment by free** [comment]
Have you tried replacing the `%` in your URL with its escaped form? I.e. `%25`? As in, replace

```
sqlserver://user:pass%word@host:3306
```

with

```
sqlserver://user:pass%25word@host:3306
```

**Comment by DandyDeveloper** [comment]
@free I had actually stupidly not realised that we were using postgresql not sqlserver, meaning the parser worked as expected for postgres. 

I suspect this works for sqlserver per your suggestion. Going to be closing this. Thank you and sorry for the delay!
