### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jvv-trackunit** [free/sql_exporter#79]
Hi

Love this project. Great work!

Can you create a new release of the exporter to include the changes made since v 0.5? I'm specifically interested in the change made in https://github.com/free/sql_exporter/pull/50.

**Comment by burningalchemist** [comment]
Hi @van-vliet! You can take a look here: https://github.com/burningalchemist/sql_exporter

I'm currently maintaining the fork, feel free to check if it works for you. 🙂

**Comment by jvv-trackunit** [comment]
Thanks @burningalchemist !

I'll take a look.
