### ISSUE TITLE
About database configuration

### ISSUE THREAD

**Issue by xiaoming199411** [free/sql_exporter#86]
Hello, everyone.

I'm having an issue with Cleartext Password when configuring a database connection.

`MySQL	mysql://user:passw@protocol(host:port)/dbname	  user:passw@protocol(host:port)/dbname`

Please let me know, When the database is configured, is it possible to encrypt the database password?

Thanks and Best Regards.

**Comment by free** [comment]
> Please let me know, When the database is configured, is it possible to encrypt the database password?

Not in the DSN you pass to SQL Exporter, no. Whatever encryption you would use, SQL Exporter would have to be able to decrypt said password; or MySQL would have to accept it in encrypted format; meaning anyone with access to the encrypted password would have access to the DB anyway.

What you can do is create a separate DB user with only enough privileges to run whatever queries you need SQL Exporter to run. And not commit your credentials (username and password) into the code repository, but instead have them populated at deployment time from a more secure location.

**Comment by Venkat2694** [comment]
I am using devops pipelines to run a ansible playbook that will create a container with sql configuration. How to populate the credentials when creating container?
