### ISSUE TITLE
Trying to get to work on MySQL

### ISSUE THREAD

**Issue by mgrahambase2** [free/sql_exporter#88]
Im trying to figure out what Im doing wrong. Ive set it up via docker

I run the following 

`docker run -it -v $(pwd):/data -p 9399:9399 -w /data  sqlexporter ./sql_exporter -config.file sql_exporter.yml`

Ive set the mysql as the following

  `data_source_name: 'mysql://user:password@protocol(127.0.0.1:3306)/dtracker'`
  
  All Im seeing is the following error 
  
  `I0122 03:43:26.207711       1 main.go:67] Listening on :9399
I0122 03:43:42.122814       1 promhttp.go:38] Error gathering metrics: [from Gatherer #1] dial protocol: unknown network protoco`

Ive tried to run debug to see what the issue might be but have no idea how to switch the debug flag

**Comment by mgrahambase2** [comment]
Figured out what I was doing wrong with the config.

**Comment by juanrosero** [comment]
@mgrahambase2 , can you share the solution to this problem please?
